/*
 * 002_ledbutton.c
 *
 *  Created on: Aug 12, 2024
 *      Author: ADMIN
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32fxx.h"

#define HIGH 1
#define BTN_PRESSED HIGH
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void delay(void){

	for(int i=0;i<500000/2;i++);
}

int main(void)
{
    /* Loop forever */

	GPIOx_Handle_t GPIOLed,GPIOBtn;
	GPIOLed.pGPIOx =GPIOD;

	GPIOLed.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_12;
	GPIOLed.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_OUT;
	GPIOLed.GPIO_PinConfig.GPIO_PinSpeed= GPIO_SPEED_FAST;
	GPIOLed.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
	GPIOLed.GPIO_PinConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOD,ENABLE);

	GPIO_Init(&GPIOLed);

	GPIOBtn.pGPIOx =GPIOA;
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_0;
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_IN;
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed= GPIO_SPEED_FAST;
	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOA,ENABLE);

	GPIO_Init(&GPIOBtn);


	for(;;){
			if(GPIO_ReadInputPin(GPIOA,GPIO_PIN_NO_0)==BTN_PRESSED){
			delay();
			GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_12);
			}


	}
	return 0;
}
