/*
 * 002_ledbutton.c
 *
 *  Created on: Aug 12, 2024
 *      Author: ADMIN
 */


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32fxx.h"

#define HIGH 1
#define LOW  0
#define BTN_PRESSED LOW
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void delay(int n){

	for(int i=0;i<n/2;i++);
}

int main(void)
{
    /* Loop forever */

	GPIOx_Handle_t GPIOLed,GPIOBtn;

	memset(&GPIOLed,0,sizeof(GPIOLed));
	memset(&GPIOBtn,0,sizeof(GPIOBtn));
	GPIOLed.pGPIOx =GPIOD;

	GPIOLed.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_12;
	GPIOLed.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_OUT;
	GPIOLed.GPIO_PinConfig.GPIO_PinSpeed= GPIO_SPEED_LOW;
	GPIOLed.GPIO_PinConfig.GPIO_PinOPType= GPIO_OP_TYPE_PP;
	GPIOLed.GPIO_PinConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;

	GPIO_PeriClockControl(GPIOD,ENABLE);

	GPIO_Init(&GPIOLed);

	GPIOBtn.pGPIOx =GPIOD;
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_IT_FT;
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed= GPIO_SPEED_FAST;
	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl= GPIO_PIN_PU;

	GPIO_PeriClockControl(GPIOD,ENABLE);

	GPIO_Init(&GPIOBtn);
	GPIO_WriteToOutputPin(GPIOD,GPIO_PIN_NO_12,GPIO_PIN_RESET);
	//IRQ Configuration
	GPIO_IRQPriorityConfig(IRQ_NO_EXTI9_5,NVIC_IRQ_PRI15);

	GPIO_IRQConfig(IRQ_NO_EXTI9_5,ENABLE);

	while(1);


	return 0;
}

void EXTI9_5_IRQHandler(void){
	delay(500000);
	GPIO_IRQHandling(GPIO_PIN_NO_5); //clearing the pending event from exti line
	GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_12);


}
